# Generated by Django 6.0.5 on 2026-05-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('HAPPY', 'Happy'), ('CALM', 'Calm'), ('LONELY', 'Lonely'), ('SAD', 'Sad'), ('ANGRY', 'Angry')], max_length=10)),
                ('category', models.CharField(choices=[('SELF', 'Self'), ('FAMILY', 'Family'), ('PET', 'Pet'), ('FRIENDS', 'Friends'), ('WORK', 'Work'), ('OTHER', 'Other')], max_length=10)),
                ('custom_category', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
