# Generated by Django 6.0.5 on 2026-05-23 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emotionlog',
            name='emotion',
            field=models.CharField(choices=[('HAPPY', '😁 Happy'), ('CALM', '☺️ Calm'), ('LONELY', '😔 Lonely'), ('SAD', '😭 Sad'), ('ANGRY', '🤬 Angry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emotionlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
