# Generated by Django 6.0.5 on 2026-05-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_emotionlog_created_at_alter_emotionlog_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlog',
            name='mood_score',
            field=models.IntegerField(default=3),
        ),
    ]
